### ISSUE TITLE
API call not working with Python3.4

### ISSUE THREAD

**Issue by pheerai** [cdown/aur#5]
In python 3.4, a `requests.Response` object doesn't provide a `read`-Method ([see here](http://docs.python-requests.org/en/latest/api/#requests.Response)). [Thus](https://docs.python.org/3/library/json.html#json.load), every call of `json.load` on such an object fails, raising an AttributeError:

``` python
>>> aur.msearch("pheerai")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/aur/query.py", line 32, in msearch
    return _generic_search(user, "msearch")
  File "/usr/lib/python3.4/site-packages/aur/query.py", line 89, in _generic_search
    res_data = _query_api(query, query_type, multi)
  File "/usr/lib/python3.4/site-packages/aur/query.py", line 111, in _query_api
    res_data = json.load(res_handle)
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
AttributeError: 'Response' object has no attribute 'read'
```

**Comment by pheerai** [comment]
The following works for me (even though its ugly as f***):

Instead of 

``` python
res_data = json.load(res_handle)
```

put the following

``` python
res_data = json.loads(str(res_handle.json()).replace("'",'"'))
```

into query.py, line 111, and be sure to get the quotes right (its " ' ", then ' " ')!

There may be lots of more efficient solutions. This one was the first I got working, but I didn't really work with JSON before, and only tested it with a small set of calls.

**Comment by cdown** [comment]
The basic fix seems to be to just use `json.loads(res_handle.text)` (`res_handle.json()` would also be fine, but it was written this way to avoid a mock...), but I need to test that some more before committing. Thanks for the report.
